### PR TITLE
Remove Andrea from copilot triage

### PR DESCRIPTION
**Pull request by lramos15**

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
FYI I'm also removed but I still get issues assigned.

**Comment by lramos15** [comment]
@Tyriar do you have an example?

**Comment by andreamah** [comment]
I can't believe that you originally spelled my name wrong
image

**Comment by Tyriar** [comment]
@lramos15 https://github.com/microsoft/vscode-copilot/issues/10054, https://github.com/microsoft/vscode-copilot/issues/9995

**Pull request merged**
